# Generated by Django 4.1.2 on 2022-10-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_question_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='query',
            field=models.CharField(max_length=50),
        ),
    ]
