# Generated by Django 4.1.2 on 2022-10-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_question_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='query',
            new_name='options',
        ),
    ]
