# Generated by Django 4.1.2 on 2022-10-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_query_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='option_names',
            field=models.CharField(default='foo', max_length=50),
            preserve_default=False,
        ),
    ]
