# Generated by Django 4.1.2 on 2022-10-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_question_options_question_option_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_names',
        ),
    ]
