# Generated by Django 4.1.2 on 2022-10-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
